-- Generated by `prisma migrate diff --from-empty --to-schema prisma/schema --script`,
-- then hand-edited to add the CHECK constraints marked "-- invariant:" below.
-- Prisma's schema language cannot express CHECK constraints, so they live here.

-- CreateTable
CREATE TABLE "Booking" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "trialClassId" TEXT NOT NULL,
    "studentId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending_payment',
    "statusReason" TEXT,
    "confirmedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Booking_trialClassId_fkey" FOREIGN KEY ("trialClassId") REFERENCES "TrialClass" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Booking_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "Student" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    -- invariant: only known statuses, and confirmedAt is set exactly when the booking is confirmed
    CONSTRAINT "Booking_status_check" CHECK ("status" IN ('pending_payment', 'confirmed', 'payment_failed', 'cancelled')),
    CONSTRAINT "Booking_confirmedAt_check" CHECK (("status" = 'confirmed') = ("confirmedAt" IS NOT NULL))
);

-- CreateTable
CREATE TABLE "Parent" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "Student" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "parentId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "age" INTEGER NOT NULL CHECK ("age" BETWEEN 3 AND 18),
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Student_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "Parent" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PaymentAttempt" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "bookingId" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "amountCents" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "providerRef" TEXT,
    "declineReason" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "PaymentAttempt_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    -- invariant: only known statuses and positive amounts
    CONSTRAINT "PaymentAttempt_status_check" CHECK ("status" IN ('authorized', 'captured', 'voided', 'declined')),
    CONSTRAINT "PaymentAttempt_amount_check" CHECK ("amountCents" > 0)
);

-- CreateTable
CREATE TABLE "TrialClass" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "subject" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "startsAt" DATETIME NOT NULL,
    "capacity" INTEGER NOT NULL DEFAULT 4,
    "confirmedCount" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- invariant: a class can never hold more confirmed students than its capacity
    CONSTRAINT "TrialClass_capacity_check" CHECK ("capacity" > 0),
    CONSTRAINT "TrialClass_confirmedCount_check" CHECK ("confirmedCount" >= 0 AND "confirmedCount" <= "capacity")
);

-- CreateIndex
CREATE INDEX "Booking_trialClassId_status_idx" ON "Booking"("trialClassId", "status");

-- CreateIndex
CREATE INDEX "Booking_studentId_idx" ON "Booking"("studentId");

-- CreateIndex
-- invariant: at most one active (pending_payment or confirmed) booking per child per class
CREATE UNIQUE INDEX "Booking_one_active_per_child_class" ON "Booking"("trialClassId", "studentId") WHERE status IN ('pending_payment', 'confirmed');

-- CreateIndex
CREATE UNIQUE INDEX "Parent_email_key" ON "Parent"("email");

-- CreateIndex
CREATE INDEX "Student_parentId_idx" ON "Student"("parentId");

-- CreateIndex
CREATE INDEX "PaymentAttempt_bookingId_idx" ON "PaymentAttempt"("bookingId");

